title: Verb / Noun
description: A literary magazine exploring the intersection of words and meaning
url: "https://verbnoun.com"
baseurl: ""

markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: ""

jekyll-minifier:
  preserve_php: true
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_intertag_spaces: true
  remove_quotes: false
  compress_css: true
  compress_javascript: true
  compress_json: true
  simple_doctype: false
  remove_script_attributes: true
  remove_style_attributes: true
  remove_link_attributes: true
  remove_form_attributes: false
  remove_input_attributes: true
  remove_javascript_protocol: true
  remove_http_protocol: false
  remove_https_protocol: false
  preserve_line_breaks: false
  simple_boolean_attributes: true


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/